### ISSUE TITLE
On signup, new user has to be placed into the Person table

### ISSUE THREAD

**Issue by jimmydeen** [jimmydeen/zen-journal#8]
At the moment only adding to the private backend "users" table for authentication purposes, but need to use the same uid ("id" column") to create a Person entry- maybe we can trigger it somewhere. Otherwise other functionality won't work (e.g. adding entry needs Person PK as FK- won't work if Person PK doesn't exist !)

**Comment by edward-20** [comment]
`public.users` and `auth.users` differ in that `public.users` has a foreign key to `auth.users`'s primary key and has the details of the user
